---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:

  - name: fetch git submodules
    image: node:14-alpine
    commands:
      - apk add git
      - git submodule init
      - git submodule update --recursive --remote
      - git fetch --tags

  - name: yarn
    image: node:14-alpine
    commands:
      - yarn

  - name: yarn lint
    image: node:14-alpine
    commands:
      - yarn lint

  - name: yarn build:dev
    image: node:14-alpine
    commands:
      - yarn build:dev

  - name: nightly build
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: dessalines/lemmy-ui
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - dev
    when:
      event:
        - cron

  - name: publish release docker image
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: dessalines/lemmy-ui
      auto_tag: true
      auto_tag_suffix: linux-amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      ref:
        - refs/tags/*

  - name: publish release docker manifest
    image: plugins/manifest
    settings: 
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: "dessalines/lemmy-ui:${DRONE_TAG}"
      template: "dessalines/lemmy-ui:${DRONE_TAG}-OS-ARCH"
      platforms:
        - linux/amd64
        - linux/arm64
      ignore_missing: true
    when:
      ref:
      - refs/tags/*

  - name: publish latest release docker manifest
    image: plugins/manifest
    settings: 
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: "dessalines/lemmy-ui:latest"
      template: "dessalines/lemmy-ui:${DRONE_TAG}-OS-ARCH"
      platforms:
        - linux/amd64
        - linux/arm64
      ignore_missing: true
    when:
      ref:
      - refs/tags/*

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:

  - name: fetch git submodules
    image: node:14-alpine
    commands:
      - apk add git
      - git submodule init
      - git submodule update --recursive --remote
      - git fetch --tags
    when:
      ref:
        - refs/heads/main
        - refs/tags/*

  - name: publish release docker image
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: dessalines/lemmy-ui
      auto_tag: true
      auto_tag_suffix: linux-arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      ref:
        - refs/tags/*

  - name: publish release docker manifest
    image: plugins/manifest
    settings: 
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: "dessalines/lemmy-ui:${DRONE_TAG}"
      template: "dessalines/lemmy-ui:${DRONE_TAG}-OS-ARCH"
      platforms:
        - linux/amd64
        - linux/arm64
      ignore_missing: true
    when:
      ref:
      - refs/tags/*

  - name: publish latest release docker manifest
    image: plugins/manifest
    settings: 
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: "dessalines/lemmy-ui:latest"
      template: "dessalines/lemmy-ui:${DRONE_TAG}-OS-ARCH"
      platforms:
        - linux/amd64
        - linux/arm64
      ignore_missing: true
    when:
      ref:
      - refs/tags/*
