variables:
  - &install_pnpm "npm i -g corepack && corepack enable pnpm"

steps:
  fetch_git_submodules:
    image: node:24-alpine
    commands:
      - apk add git
      - git submodule init
      - git submodule update
    when:
      - event: [pull_request, tag]

  prettier_check:
    image: tmknom/prettier:3.6.2
    commands:
      - prettier -c .
    when:
      - event: pull_request

  bash_fmt:
    image: alpine:3
    commands:
      - apk add shfmt
      - shfmt -i 2 -d */**.bash
      - shfmt -i 2 -d */**.sh
    when:
      - event: pull_request

  install:
    image: node:24-alpine
    commands:
      - *install_pnpm
      - pnpm i
    when:
      - event: pull_request

  lint:
    image: node:24-alpine
    commands:
      - *install_pnpm
      - pnpm lint
    when:
      - event: pull_request

  build_dev:
    image: node:24-alpine
    commands:
      - *install_pnpm
      - pnpm prebuild:dev
      - pnpm build:dev
    when:
      - event: pull_request

  publish_release_docker:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: dessalines/lemmy-ui
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms: linux/amd64,linux/arm64
      tag: ${CI_COMMIT_TAG}
    when:
      - event: tag

  nightly_build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: dessalines/lemmy-ui
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      platforms: linux/amd64,linux/arm64
      tag: dev
    when:
      - event: cron

  notify_success:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -H'Title: ✔️ ${CI_REPO_NAME}/${CI_COMMIT_SOURCE_BRANCH}' -d'${CI_PIPELINE_URL}' ntfy.sh/lemmy_drone_ci"
    when:
      - event: pull_request
        status: [success]

  notify_failure:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -H'Title: ❌ ${CI_REPO_NAME}/${CI_COMMIT_SOURCE_BRANCH}' -d'${CI_PIPELINE_URL}' ntfy.sh/lemmy_drone_ci"
    when:
      - event: pull_request
        status: [failure]

  notify_on_tag_deploy:
    image: alpine:3
    commands:
      - apk add curl
      - "curl -H'Title: ${CI_REPO_NAME}:${CI_COMMIT_TAG} deployed' -d'${CI_PIPELINE_URL}' ntfy.sh/lemmy_drone_ci"
    when:
      event: tag
