name: "\U0001F41E Bug Report"
description: Create a report to help us improve lemmy-ui
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Found a bug? Please fill out the sections below. 👍
        Thanks for taking the time to fill out this bug report!
        For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)
  - type: checkboxes
    attributes:
      label: Requirements
      description: Before you create a bug report please do the following.
      options:
        - label: Did you check to see if this issue already exists?
        - label: Is this only a single bug. Do not put multiple bugs in one issue.
        - label: Is this a question or discussion? Don't use this, use https://lemmy.ml/c/lemmy_support
        - label: Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A summary of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Describe the steps to reproduce the bug.
        The better your description is _(go 'here', click 'there'...)_ the fastest you'll get an _(accurate)_ resolution. 
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: technical
    attributes:
      label: Technical Details
      description: |
        - Any browser console errors?
    validations:
      required: true
  - type: input
    id: lemmy-ui-version
    attributes:
      label: Version
      description: Which Lemmy UI version do you use? Displayed in the footer.
      placeholder: ex. 0.17.4-rc.4
    validations:
      required: true
