name: "\U0001F680 Feature request"
description: Suggest an idea for Lemmy-UI.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help improve Lemmy-UI by suggesting a feature!
  - type: checkboxes
    attributes:
      label: Requirements
      description: Before you create a feature request, please carefully check the following –
      options:
        - label: This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
          required: true
        - label: Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
          required: true
        - label: It's a single feature. Please don't request multiple features in one issue.
          required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the feature you'd like
      description: |
        Provide a clear and concise description of the feature. Explain why it's needed.
    validations:
      required: true
