name: "Hexbear"
description: For hexbear issues
title: ""
labels: ["hexbear", "triage"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What's the question you have about hexbear?
    validations:
      required: true